---
- name: Install Config
  template: src=defaults.j2 dest=/etc/default/selenium_{{sel_role}} owner=root group=root mode=644
  tags: ['config']

- name: Install Xvfb init script
  template: src=xvfb_initd.j2 dest=/etc/init.d/xvfb owner=root group=root mode=755
  tags: ['config']

- name: Install init script
  template: src=selenium.init.j2 dest=/etc/init.d/selenium_{{sel_role}} owner=root group=root mode=755
  tags: ['config']

- name: selenium_started
  service: name=selenium_{{sel_role}} state=started 

- name: xvfb_started
  service: name=xvfb state=started 
  when: sel_role != 'hub'

