
---
- name: selenium_started
  service: name=selenium_{{sel_role}} state=started enabled=yes

- name: selenium_reload
  service: name=selenium_{{sel_role}} state=reloaded

- name: xvfb_started
  service: name=xvfb state=started enabled=yes
